language: ruby

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - jruby-1.7.16
  - jruby-head

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

matrix:
  allow_failures:
    - rvm: jruby-head
  exclude:
    # JRuby 9k needs Java7 :
    - rvm: jruby-head
      jdk: openjdk6
